<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/aws/aws-sdk-php/src/functions.php';
require_once __DIR__ . '/guzzlehttp/guzzle/src/functions_include.php';
require_once __DIR__ . '/symfony/polyfill-intl-idn/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-intl-normalizer/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php72/bootstrap.php';
require_once __DIR__ . '/guzzlehttp/promises/src/functions_include.php';
require_once __DIR__ . '/guzzlehttp/psr7/src/functions_include.php';
require_once __DIR__ . '/ralouphie/getallheaders/src/getallheaders.php';
require_once __DIR__ . '/mtdowling/jmespath.php/src/JmesPath.php';
require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
require_once __DIR__ . '/google/apiclient/src/aliases.php';
require_once __DIR__ . '/google/apiclient-services/autoload.php';
require_once __DIR__ . '/phpseclib/phpseclib/phpseclib/bootstrap.php';
